services:
  mysql:
    image: mysql:8.0
    container_name: supplierhub_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: supplierhub
      MYSQL_USER: supplierhub_user
      MYSQL_PASSWORD: supplierhub_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./sql/stored_procedures.sql:/docker-entrypoint-initdb.d/03-procedures.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake

volumes:
  mysql_data:
